[server_config]
host = "127.0.0.1"     # Optional in TOML, can be overridden by env var `VSS_SERVER_HOST`
port = 8080            # Optional in TOML, can be overridden by env var `VSS_SERVER_PORT`
# jwt_public_key = """your_public_RSA_key_in_PEM_format""" # Optional in TOML, can be overridden by env var `VSS_JWT_PUBLIC_KEY`

[postgresql_config]
username = "postgres"  # Optional in TOML, can be overridden by env var `VSS_POSTGRESQL_USERNAME`
password = "postgres"  # Optional in TOML, can be overridden by env var `VSS_POSTGRESQL_PASSWORD`
host = "localhost"     # Optional in TOML, can be overridden by env var `VSS_POSTGRESQL_HOST`
port = 5432            # Optional in TOML, can be overridden by env var `VSS_POSTGRESQL_PORT`
database = "postgres"  # Optional in TOML, can be overridden by env var `VSS_POSTGRESQL_DATABASE`
